[package]
name = "feluda"
version = "1.4.0"
edition = "2021"
description = "A CLI tool to check dependency licenses."
readme = "README.md"
license = "MIT"
repository = "https://github.com/anistark/feluda"
homepage = "https://github.com/anistark/feluda"
keywords = ["cli", "license", "dependencies", "node", "check"]
categories = ["command-line-utilities", "development-tools"]
include = ["src/**", "Cargo.toml", "README.md", "LICENSE"]
documentation = "https://docs.rs/feluda"

[dependencies]
cargo_metadata = "0.19.1"
clap = { version = "4.5.26", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12.12", default-features = false, features = [
    "json",
    "blocking",
    "rustls-tls",
] }
serde_json = "1.0.135"
scraper = "0.22.0"
color-eyre = "0.6.3"
ratatui = "0.29.0"
unicode-width = "0.2.0"
spinners = "4.1.1"
serde_yaml = "0.9.34"
colored = "3.0.0"
rayon = "1.10.0"
figment = { version = "0.10", features = ["toml", "env"] }

[dev-dependencies]
tempfile = "3.2"
mockall = "0.13.1"
http = "1.2.0"
temp-env = "0.3.1"

[[bin]]
name = "feluda"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
